                                                                                Practical 06 -II SVM

NAME:KETAN POLWAR

ROLL NO :40

AIM :-
Create a machine learning model to predict whether a person survived in Titanic or not.

1 Perform the EDA

2 Apply Naive Bayes classifier 

3 Apply SVM

4 Apply RF

5 Evaluate the performance using Precision, Recall, F1 score and accuracy.

6 Apply hyper parameter tuning to improve performance.

In [11]:
import os
os.getcwd()

'c:\\Users\\DHANSHRI\\OneDrive\\Desktop\\Acedemics\\fourth\\vs backup'

In [12]:
import pandas as pd
import numpy as np

In [13]:
df=pd.read_csv("tan.csv")

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [15]:
df.drop(['Name','SibSp','Parch','Embarked'], axis=1,inplace=True)

In [16]:
df

,PassengerId,Survived,Pclass,Sex,Age,Ticket,Fare,Cabin
0,1,0,3,male,22.0,A/5 21171,7.2500,NaN
1,2,1,1,female,38.0,PC 17599,71.2833,C85
2,3,1,3,female,26.0,STON/O2. 3101282,7.9250,NaN
3,4,1,1,female,35.0,113803,53.1000,C123
4,5,0,3,male,35.0,373450,8.0500,NaN
...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,211536,13.0000,NaN
887,888,1,1,female,19.0,112053,30.0000,B42
888,889,0,3,female,NaN,W./C. 6607,23.4500,NaN
889,890,1,1,male,26.0,111369,30.0000,C148
890,891,0,3,male,32.0,370376,7.7500,NaN

In [17]:
df.drop(['Ticket','Cabin'], axis=1,inplace=True)

In [18]:
df

     PassengerId  Survived  Pclass     Sex   Age     Fare
0              1         0       3    male  22.0   7.2500
1              2         1       1  female  38.0  71.2833
2              3         1       3  female  26.0   7.9250
3              4         1       1  female  35.0  53.1000
4              5         0       3    male  35.0   8.0500
..           ...       ...     ...     ...   ...      ...
886          887         0       2    male  27.0  13.0000
887          888         1       1  female  19.0  30.0000
888          889         0       3  female   NaN  23.4500
889          890         1       1    male  26.0  30.0000
890          891         0       3    male  32.0   7.7500

[891 rows x 6 columns]

In [19]:
df.isnull()

     PassengerId  Survived  Pclass    Sex    Age   Fare
0          False     False   False  False  False  False
1          False     False   False  False  False  False
2          False     False   False  False  False  False
3          False     False   False  False  False  False
4          False     False   False  False  False  False
..           ...       ...     ...    ...    ...    ...
886        False     False   False  False  False  False
887        False     False   False  False  False  False
888        False     False   False  False   True  False
889        False     False   False  False  False  False
890        False     False   False  False  False  False

[891 rows x 6 columns]

In [20]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
Fare             0
dtype: int64

In [21]:
mean = df["Age"].mean()

In [22]:
df["Age"].fillna(mean, inplace = True)

In [23]:
df

     PassengerId  Survived  Pclass     Sex        Age     Fare
0              1         0       3    male  22.000000   7.2500
1              2         1       1  female  38.000000  71.2833
2              3         1       3  female  26.000000   7.9250
3              4         1       1  female  35.000000  53.1000
4              5         0       3    male  35.000000   8.0500
..           ...       ...     ...     ...        ...      ...
886          887         0       2    male  27.000000  13.0000
887          888         1       1  female  19.000000  30.0000
888          889         0       3  female  29.699118  23.4500
889          890         1       1    male  26.000000  30.0000
890          891         0       3    male  32.000000   7.7500

[891 rows x 6 columns]

In [24]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
Fare           0
dtype: int64

In [25]:
df['PassengerId'].duplicated().sum()

0

In [26]:
df.drop(['Fare'], axis=1,inplace=True)

In [27]:
#df.loc[df["Sex"]=="female"]=0
#df.loc[df["Sex"]=="male"]=1

In [28]:
df

     PassengerId  Survived  Pclass     Sex        Age
0              1         0       3    male  22.000000
1              2         1       1  female  38.000000
2              3         1       3  female  26.000000
3              4         1       1  female  35.000000
4              5         0       3    male  35.000000
..           ...       ...     ...     ...        ...
886          887         0       2    male  27.000000
887          888         1       1  female  19.000000
888          889         0       3  female  29.699118
889          890         1       1    male  26.000000
890          891         0       3    male  32.000000

[891 rows x 5 columns]

In [29]:
df['Sex'].replace({'male':0,'female':'1'},inplace=True)

In [30]:
df

     PassengerId  Survived  Pclass Sex        Age
0              1         0       3   0  22.000000
1              2         1       1   1  38.000000
2              3         1       3   1  26.000000
3              4         1       1   1  35.000000
4              5         0       3   0  35.000000
..           ...       ...     ...  ..        ...
886          887         0       2   0  27.000000
887          888         1       1   1  19.000000
888          889         0       3   1  29.699118
889          890         1       1   0  26.000000
890          891         0       3   0  32.000000

[891 rows x 5 columns]

In [31]:
target = df.Survived

In [32]:
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [33]:
data = df.drop('Survived',axis=1)

In [34]:
data

     PassengerId  Pclass Sex        Age
0              1       3   0  22.000000
1              2       1   1  38.000000
2              3       3   1  26.000000
3              4       1   1  35.000000
4              5       3   0  35.000000
..           ...     ...  ..        ...
886          887       2   0  27.000000
887          888       1   1  19.000000
888          889       3   1  29.699118
889          890       1   0  26.000000
890          891       3   0  32.000000

[891 rows x 4 columns]

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

In [36]:
x_train,x_test,y_train,y_test = train_test_split(data,target,test_size=0.2)

In [37]:
x_train,x_test,y_train,y_test

(     PassengerId  Pclass Sex        Age
 8              9       3   1  27.000000
 223          224       3   0  29.699118
 603          604       3   0  44.000000
 795          796       2   0  39.000000
 229          230       3   1  29.699118
 ..           ...     ...  ..        ...
 43            44       2   1   3.000000
 661          662       3   0  40.000000
 162          163       3   0  26.000000
 6              7       1   0  54.000000
 489          490       3   0   9.000000

 [712 rows x 4 columns],
      PassengerId  Pclass Sex        Age
 677          678       3   1  18.000000
 534          535       3   1  30.000000
 198          199       3   1  29.699118
 540          541       1   1  36.000000
 1              2       1   1  38.000000
 ..           ...     ...  ..        ...
 194          195       1   1  44.000000
 669          670       1   1  29.699118
 774          775       2   1  54.000000
 768          769       3   0  29.699118
 486          487       1   1  35.000000

 [179 rows x 4 columns],
 8      1
 223    0
 603    0
 795    0
 229    0
       ..
 43     1
 661    0
 162    0
 6      0
 489    1
 Name: Survived, Length: 712, dtype: int64,
 677    1
 534    0
 198    1
 540    1
 1      1
       ..
 194    1
 669    1
 774    1
 768    0
 486    1
 Name: Survived, Length: 179, dtype: int64)

In [38]:
len(x_train)

712

In [44]:
from sklearn import svm#support vector margin(hyperplane)
model=svm.SVC()
model.fit(x_train,y_train)
model.score(x_test,y_test)
y_prediction=model.predict(x_test)

In [45]:

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_prediction,labels=model.classes_)

In [47]:
from sklearn.metrics import classification_report#liner poly and rbf kernel (rbf does the infine dimension ) ,gamma will decide grouping, c define decision boundries
print(classification_report(y_test,y_prediction))

              precision    recall  f1-score   support

           0       0.60      1.00      0.75       108
           1       0.00      0.00      0.00        71

    accuracy                           0.60       179
   macro avg       0.30      0.50      0.38       179
weighted avg       0.36      0.60      0.45       179

c:\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [53]:
from sklearn import svm#support vector margin(hyperplane)
model1=svm.SVC(kernel='linear',gamma='auto',C=21)
model1.fit(x_train,y_train)
model1.score(x_test,y_test)
y_prediction=model.predict(x_test)

In [54]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_prediction,labels=model1.classes_)

In [55]:
from sklearn.metrics import classification_report#liner poly and rbf kernel (rbf does the infine dimension ) ,gamma will decide grouping, c define decision boundries
print(classification_report(y_test,y_prediction))

              precision    recall  f1-score   support

           0       0.78      0.91      0.84       108
           1       0.81      0.61      0.69        71

    accuracy                           0.79       179
   macro avg       0.79      0.76      0.77       179
weighted avg       0.79      0.79      0.78       179

In [60]:
param_grid={'C':[0.1,1,10,100,1000],'gamma':[1.0,1,0.01,0.001,1000],'kernel':['rbf']}
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(model,param_grid,refit=True,verbose=3) 
grid.fit(x_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ......C=0.1, gamma=1.0, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=1.0, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=1000, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=1000, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END ........C=1, gamma=1.0, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END ........C=1, gamma=1.0, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ........C=1, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ........C=1, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ........C=1, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.573 total time=   0.0s
[CV 2/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.559 total time=   0.0s
[CV 3/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.592 total time=   0.0s
[CV 4/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.528 total time=   0.0s
[CV 5/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.585 total time=   0.0s
[CV 1/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.601 total time=   0.0s
[CV 2/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.559 total time=   0.0s
[CV 3/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.592 total time=   0.0s
[CV 4/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.570 total time=   0.0s
[CV 5/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.599 total time=   0.0s
[CV 1/5] END .......C=1, gamma=1000, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END .......C=1, gamma=1000, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END .......C=1, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END .......C=1, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END .......C=1, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END .......C=10, gamma=1.0, kernel=rbf;, score=0.622 total time=   0.0s
[CV 2/5] END .......C=10, gamma=1.0, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END .......C=10, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END .......C=10, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END .......C=10, gamma=1.0, kernel=rbf;, score=0.606 total time=   0.0s
[CV 1/5] END .........C=10, gamma=1, kernel=rbf;, score=0.622 total time=   0.0s
[CV 2/5] END .........C=10, gamma=1, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END .........C=10, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END .........C=10, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END .........C=10, gamma=1, kernel=rbf;, score=0.606 total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.545 total time=   0.0s
[CV 2/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.538 total time=   0.0s
[CV 3/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.585 total time=   0.0s
[CV 4/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.521 total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.556 total time=   0.0s
[CV 1/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.636 total time=   0.0s
[CV 2/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.580 total time=   0.0s
[CV 3/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.599 total time=   0.0s
[CV 4/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.521 total time=   0.0s
[CV 5/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.577 total time=   0.0s
[CV 1/5] END ......C=10, gamma=1000, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END ......C=10, gamma=1000, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ......C=10, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ......C=10, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ......C=10, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END ......C=100, gamma=1.0, kernel=rbf;, score=0.622 total time=   0.0s
[CV 2/5] END ......C=100, gamma=1.0, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ......C=100, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ......C=100, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ......C=100, gamma=1.0, kernel=rbf;, score=0.606 total time=   0.0s
[CV 1/5] END ........C=100, gamma=1, kernel=rbf;, score=0.622 total time=   0.0s
[CV 2/5] END ........C=100, gamma=1, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ........C=100, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ........C=100, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ........C=100, gamma=1, kernel=rbf;, score=0.606 total time=   0.0s
[CV 1/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.552 total time=   0.0s
[CV 2/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.490 total time=   0.0s
[CV 3/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.606 total time=   0.0s
[CV 4/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.507 total time=   0.0s
[CV 5/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.563 total time=   0.0s
[CV 1/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.671 total time=   0.0s
[CV 2/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.657 total time=   0.0s
[CV 3/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.627 total time=   0.0s
[CV 4/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.690 total time=   0.0s
[CV 1/5] END .....C=100, gamma=1000, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END .....C=100, gamma=1000, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END .....C=100, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END .....C=100, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END .....C=100, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END .....C=1000, gamma=1.0, kernel=rbf;, score=0.622 total time=   0.0s
[CV 2/5] END .....C=1000, gamma=1.0, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END .....C=1000, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END .....C=1000, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END .....C=1000, gamma=1.0, kernel=rbf;, score=0.606 total time=   0.0s
[CV 1/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.622 total time=   0.0s
[CV 2/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.606 total time=   0.0s
[CV 1/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.538 total time=   0.0s
[CV 2/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.524 total time=   0.0s
[CV 3/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.599 total time=   0.0s
[CV 4/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.507 total time=   0.0s
[CV 5/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.549 total time=   0.0s
[CV 1/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.678 total time=   0.0s
[CV 2/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.601 total time=   0.0s
[CV 3/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.641 total time=   0.0s
[CV 4/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.634 total time=   0.0s
[CV 5/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.739 total time=   0.0s
[CV 1/5] END ....C=1000, gamma=1000, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END ....C=1000, gamma=1000, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ....C=1000, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ....C=1000, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ....C=1000, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s

GridSearchCV(estimator=SVC(C=21, gamma='auto', kernel='linear'),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1.0, 1, 0.01, 0.001, 1000],
                         'kernel': ['rbf']},
             verbose=3)

In [61]:
param_grid={'C':[0.1,1,10,100,1000],'gamma':[1.0,1,0.01,0.001,1000],'kernel':['rbf']}
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(model1,param_grid,refit=True,verbose=3)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ......C=0.1, gamma=1.0, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=1.0, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=1000, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=1000, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END ........C=1, gamma=1.0, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END ........C=1, gamma=1.0, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ........C=1, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ........C=1, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ........C=1, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.573 total time=   0.0s
[CV 2/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.559 total time=   0.0s
[CV 3/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.592 total time=   0.0s
[CV 4/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.528 total time=   0.0s
[CV 5/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.585 total time=   0.0s
[CV 1/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.601 total time=   0.0s
[CV 2/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.559 total time=   0.0s
[CV 3/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.592 total time=   0.0s
[CV 4/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.570 total time=   0.0s
[CV 5/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.599 total time=   0.0s
[CV 1/5] END .......C=1, gamma=1000, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END .......C=1, gamma=1000, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END .......C=1, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END .......C=1, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END .......C=1, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END .......C=10, gamma=1.0, kernel=rbf;, score=0.622 total time=   0.0s
[CV 2/5] END .......C=10, gamma=1.0, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END .......C=10, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END .......C=10, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END .......C=10, gamma=1.0, kernel=rbf;, score=0.606 total time=   0.0s
[CV 1/5] END .........C=10, gamma=1, kernel=rbf;, score=0.622 total time=   0.0s
[CV 2/5] END .........C=10, gamma=1, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END .........C=10, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END .........C=10, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END .........C=10, gamma=1, kernel=rbf;, score=0.606 total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.545 total time=   0.0s
[CV 2/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.538 total time=   0.0s
[CV 3/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.585 total time=   0.0s
[CV 4/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.521 total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.556 total time=   0.0s
[CV 1/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.636 total time=   0.0s
[CV 2/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.580 total time=   0.0s
[CV 3/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.599 total time=   0.0s
[CV 4/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.521 total time=   0.0s
[CV 5/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.577 total time=   0.0s
[CV 1/5] END ......C=10, gamma=1000, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END ......C=10, gamma=1000, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ......C=10, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ......C=10, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ......C=10, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END ......C=100, gamma=1.0, kernel=rbf;, score=0.622 total time=   0.0s
[CV 2/5] END ......C=100, gamma=1.0, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ......C=100, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ......C=100, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ......C=100, gamma=1.0, kernel=rbf;, score=0.606 total time=   0.0s
[CV 1/5] END ........C=100, gamma=1, kernel=rbf;, score=0.622 total time=   0.0s
[CV 2/5] END ........C=100, gamma=1, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ........C=100, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ........C=100, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ........C=100, gamma=1, kernel=rbf;, score=0.606 total time=   0.0s
[CV 1/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.552 total time=   0.0s
[CV 2/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.490 total time=   0.0s
[CV 3/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.606 total time=   0.0s
[CV 4/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.507 total time=   0.0s
[CV 5/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.563 total time=   0.0s
[CV 1/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.671 total time=   0.0s
[CV 2/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.657 total time=   0.0s
[CV 3/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.627 total time=   0.0s
[CV 4/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.690 total time=   0.0s
[CV 1/5] END .....C=100, gamma=1000, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END .....C=100, gamma=1000, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END .....C=100, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END .....C=100, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END .....C=100, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 1/5] END .....C=1000, gamma=1.0, kernel=rbf;, score=0.622 total time=   0.0s
[CV 2/5] END .....C=1000, gamma=1.0, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END .....C=1000, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END .....C=1000, gamma=1.0, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END .....C=1000, gamma=1.0, kernel=rbf;, score=0.606 total time=   0.0s
[CV 1/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.622 total time=   0.0s
[CV 2/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.606 total time=   0.0s
[CV 1/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.538 total time=   0.0s
[CV 2/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.524 total time=   0.0s
[CV 3/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.599 total time=   0.0s
[CV 4/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.507 total time=   0.0s
[CV 5/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.549 total time=   0.0s
[CV 1/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.678 total time=   0.0s
[CV 2/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.601 total time=   0.0s
[CV 3/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.641 total time=   0.0s
[CV 4/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.634 total time=   0.0s
[CV 5/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.739 total time=   0.0s
[CV 1/5] END ....C=1000, gamma=1000, kernel=rbf;, score=0.615 total time=   0.0s
[CV 2/5] END ....C=1000, gamma=1000, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ....C=1000, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 4/5] END ....C=1000, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s
[CV 5/5] END ....C=1000, gamma=1000, kernel=rbf;, score=0.620 total time=   0.0s

GridSearchCV(estimator=SVC(C=21, gamma='auto', kernel='linear'),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1.0, 1, 0.01, 0.001, 1000],
                         'kernel': ['rbf']},
             verbose=3)

In [62]:
grid.best_params_

{'C': 1000, 'gamma': 0.001, 'kernel': 'rbf'}

In [67]:
from sklearn import svm#support vector margin(hyperplane)
model2=svm.SVC(kernel='rbf',gamma=0.001,C=1000)
model2.fit(x_train,y_train)
model2.score(x_test,y_test)
y_predict=model.predict(x_test)

In [68]:
y_predict=model.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict,labels=model.classes_)

In [70]:
from sklearn.metrics import classification_report#liner poly and rbf kernel (rbf does the infine dimension ) ,gamma will decide grouping, c define decision boundries
print(classification_report(y_test,y_prediction))

              precision    recall  f1-score   support

           0       0.78      0.91      0.84       108
           1       0.81      0.61      0.69        71

    accuracy                           0.79       179
   macro avg       0.79      0.76      0.77       179
weighted avg       0.79      0.79      0.78       179